/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.registration.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UserEntry service. Represents a row in the &quot;REGIS_UserEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.registration.model.impl.UserEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.registration.model.impl.UserEntryImpl</code>.
 * </p>
 *
 * @author quanhuynh
 * @see UserEntry
 * @generated
 */
@ProviderType
public interface UserEntryModel extends BaseModel<UserEntry>, MVCCModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user entry model instance should use the {@link UserEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this user entry.
	 *
	 * @return the primary key of this user entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user entry.
	 *
	 * @param primaryKey the primary key of this user entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this user entry.
	 *
	 * @return the mvcc version of this user entry
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this user entry.
	 *
	 * @param mvccVersion the mvcc version of this user entry
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this user entry.
	 *
	 * @return the uuid of this user entry
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this user entry.
	 *
	 * @param uuid the uuid of this user entry
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the user entry ID of this user entry.
	 *
	 * @return the user entry ID of this user entry
	 */
	public long getUserEntryId();

	/**
	 * Sets the user entry ID of this user entry.
	 *
	 * @param userEntryId the user entry ID of this user entry
	 */
	public void setUserEntryId(long userEntryId);

	/**
	 * Returns the home phone of this user entry.
	 *
	 * @return the home phone of this user entry
	 */
	@AutoEscape
	public String getHomePhone();

	/**
	 * Sets the home phone of this user entry.
	 *
	 * @param homePhone the home phone of this user entry
	 */
	public void setHomePhone(String homePhone);

	/**
	 * Returns the mobile phone of this user entry.
	 *
	 * @return the mobile phone of this user entry
	 */
	@AutoEscape
	public String getMobilePhone();

	/**
	 * Sets the mobile phone of this user entry.
	 *
	 * @param mobilePhone the mobile phone of this user entry
	 */
	public void setMobilePhone(String mobilePhone);

	/**
	 * Returns the address1 of this user entry.
	 *
	 * @return the address1 of this user entry
	 */
	@AutoEscape
	public String getAddress1();

	/**
	 * Sets the address1 of this user entry.
	 *
	 * @param address1 the address1 of this user entry
	 */
	public void setAddress1(String address1);

	/**
	 * Returns the address2 of this user entry.
	 *
	 * @return the address2 of this user entry
	 */
	@AutoEscape
	public String getAddress2();

	/**
	 * Sets the address2 of this user entry.
	 *
	 * @param address2 the address2 of this user entry
	 */
	public void setAddress2(String address2);

	/**
	 * Returns the city of this user entry.
	 *
	 * @return the city of this user entry
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this user entry.
	 *
	 * @param city the city of this user entry
	 */
	public void setCity(String city);

	/**
	 * Returns the state of this user entry.
	 *
	 * @return the state of this user entry
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this user entry.
	 *
	 * @param state the state of this user entry
	 */
	public void setState(String state);

	/**
	 * Returns the zip code of this user entry.
	 *
	 * @return the zip code of this user entry
	 */
	@AutoEscape
	public String getZipCode();

	/**
	 * Sets the zip code of this user entry.
	 *
	 * @param zipCode the zip code of this user entry
	 */
	public void setZipCode(String zipCode);

	/**
	 * Returns the user ID of this user entry.
	 *
	 * @return the user ID of this user entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user entry.
	 *
	 * @param userId the user ID of this user entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user entry.
	 *
	 * @return the user uuid of this user entry
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user entry.
	 *
	 * @param userUuid the user uuid of this user entry
	 */
	public void setUserUuid(String userUuid);

}